apiVersion: v1
kind: Secret
metadata:
  labels:
    app: kubeclarity-kubeclarity
  name: kubeclarity-postgresql-secret-local
  namespace: kubeclarity
type: Opaque
data:
  postgres-database: base64
  postgres-host:  base64
  postgres-password: base64
  postgres-port: base64
  postgres-sslmode: base64
  postgres-username: base64
